import { resolve, dirname, relative } from 'node:path'
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { spawnSync } from 'node:child_process'

const BRIDGE_FILENAME = 'openshop-operations.d.ts'

/** Shopify custom scalars — the preset outputs `any`, we patch to real types */
const SCALAR_TYPES: Record<string, string> = {
  ARN: 'string',
  BigInt: 'string',
  Color: 'string',
  Date: 'string',
  DateTime: 'string',
  Decimal: 'string',
  FormattedString: 'string',
  HTML: 'string',
  JSON: 'string',
  Money: 'string',
  StorefrontID: 'string',
  URL: 'string',
  UnsignedInt64: 'string',
  UtcOffset: 'string',
}

export function findConfig(cwd: string): string | null {
  if (existsSync(resolve(cwd, '.graphqlrc.ts'))) return resolve(cwd, '.graphqlrc.ts')
  if (existsSync(resolve(cwd, 'codegen.ts'))) return resolve(cwd, 'codegen.ts')
  return null
}

export function findBin(cwd: string): string | null {
  const binPath = resolve(cwd, 'node_modules', '.bin', 'graphql-codegen')
  return existsSync(binPath) ? binPath : null
}

export function runCodegenOnce(cwd: string, options?: { optional?: boolean }) {
  const configPath = findConfig(cwd)
  const binPath = findBin(cwd)

  if (!configPath) {
    if (options?.optional) return false
    throw new Error('[openshop] GraphQL codegen requires .graphqlrc.ts or codegen.ts.')
  }
  if (!binPath) throw new Error('[openshop] GraphQL codegen requires @graphql-codegen/cli in the project dependencies.')

  console.log('[openshop] Running GraphQL codegen...')
  const result = spawnSync(binPath, ['--config', configPath], {
    cwd,
    stdio: 'inherit',
  })

  if (result.error) throw result.error
  if (result.status !== 0) {
    throw new Error(`[openshop] Codegen failed (exit ${result.status ?? 1})`)
  }

  patchScalars(cwd)
  generateBridge(cwd)
  console.log('[openshop] Types generated.')
  return true
}

export function findGeneratedFile(cwd: string): string | null {
  const candidates = [
    resolve(cwd, 'types/generated/admin.generated.d.ts'),
    resolve(cwd, 'generated/admin.generated.d.ts'),
  ]
  return candidates.find(existsSync) ?? null
}

export function findTypesFile(cwd: string): string | null {
  const candidates = [
    resolve(cwd, 'types/generated/admin.types.d.ts'),
    resolve(cwd, 'generated/admin.types.d.ts'),
  ]
  return candidates.find(existsSync) ?? null
}

export function patchScalars(cwd: string) {
  const typesPath = findTypesFile(cwd)
  if (!typesPath) return

  let content = readFileSync(typesPath, 'utf-8')
  let patched = false

  for (const [name, tsType] of Object.entries(SCALAR_TYPES)) {
    const pattern = new RegExp(`(${name}:\\s*\\{\\s*input:\\s*)any(;\\s*output:\\s*)any`, 'g')
    const replacement = `$1${tsType}$2${tsType}`
    const next = content.replace(pattern, replacement)
    if (next !== content) {
      content = next
      patched = true
    }
  }

  if (patched) {
    writeFileSync(typesPath, content)
    console.log('[openshop] Patched Shopify scalar types (any → string)')
  }
}

export function generateBridge(cwd: string) {
  const generatedPath = findGeneratedFile(cwd)
  if (!generatedPath) return

  const content = readFileSync(generatedPath, 'utf-8')

  const queryEntries = extractInterfaceEntries(content, 'GeneratedQueryTypes')
  const mutationEntries = extractInterfaceEntries(content, 'GeneratedMutationTypes')

  if (!queryEntries.length && !mutationEntries.length) return

  const typeNames = new Set<string>()
  for (const entry of [...queryEntries, ...mutationEntries]) {
    const matches = entry.match(/\b([A-Z]\w+(?:Query|Mutation|Variables|QueryVariables|MutationVariables))\b/g)
    if (matches) matches.forEach((m) => typeNames.add(m))
  }

  const generatedDir = dirname(generatedPath)
  const bridgePath = resolve(generatedDir, '..', BRIDGE_FILENAME)
  const relImport = './' + relative(dirname(bridgePath), generatedPath).replace(/\.d\.ts$/, '').replace(/\\/g, '/')

  const lines = [
    '// Auto-generated by openshop codegen — DO NOT EDIT',
    `import type { ${[...typeNames].join(', ')} } from '${relImport}'`,
    '',
    'declare global {',
  ]

  if (queryEntries.length) {
    lines.push('  interface OpenShopQueries {')
    for (const entry of queryEntries) lines.push(`    ${entry}`)
    lines.push('  }')
  }

  if (mutationEntries.length) {
    if (queryEntries.length) lines.push('')
    lines.push('  interface OpenShopMutations {')
    for (const entry of mutationEntries) lines.push(`    ${entry}`)
    lines.push('  }')
  }

  lines.push('}', '')

  const bridgeContent = lines.join('\n')
  const existing = existsSync(bridgePath) ? readFileSync(bridgePath, 'utf-8') : ''
  if (bridgeContent !== existing) {
    writeFileSync(bridgePath, bridgeContent)
    console.log(`[openshop] Generated ${BRIDGE_FILENAME}`)
  }
}

/**
 * Extract entries from a TypeScript interface block in a .d.ts file.
 * Handles nested braces (e.g. `{return: Type, variables: VarsType}`).
 */
export function extractInterfaceEntries(content: string, interfaceName: string): string[] {
  const startPattern = new RegExp(`interface\\s+${interfaceName}\\s*\\{`)
  const startMatch = startPattern.exec(content)
  if (!startMatch) return []

  let depth = 1
  let pos = startMatch.index + startMatch[0].length
  const start = pos
  while (pos < content.length && depth > 0) {
    if (content[pos] === '{') depth++
    else if (content[pos] === '}') depth--
    pos++
  }

  const body = content.slice(start, pos - 1)
  return body
    .split('\n')
    .map((line) => line.trim())
    .filter((line) => line.length > 0 && !line.startsWith('//') && !line.startsWith('/*') && !line.startsWith('*'))
}
