import { test } from '@japa/runner'
import { existsSync, mkdtempSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { dirname, join, resolve } from 'node:path'
import {
  extractInterfaceEntries,
  findBin,
  findConfig,
  findGeneratedFile,
  findTypesFile,
  generateBridge,
  patchScalars,
} from '../../../src/vite/codegen-utils.js'

function write(path: string, content = '') {
  mkdirSync(dirname(path), { recursive: true })
  writeFileSync(path, content)
}

test.group('codegen-utils', (group) => {
  let cwd = ''

  group.each.setup(() => {
    cwd = mkdtempSync(join(tmpdir(), 'openshop-codegen-'))
    return () => rmSync(cwd, { recursive: true, force: true })
  })

  test('finds config files in precedence order', ({ assert }) => {
    assert.isNull(findConfig(cwd))

    const codegenPath = resolve(cwd, 'codegen.ts')
    write(codegenPath)
    assert.equal(findConfig(cwd), codegenPath)

    const graphqlrcPath = resolve(cwd, '.graphqlrc.ts')
    write(graphqlrcPath)
    assert.equal(findConfig(cwd), graphqlrcPath)
  })

  test('finds local codegen binary when installed', ({ assert }) => {
    assert.isNull(findBin(cwd))

    const binPath = resolve(cwd, 'node_modules/.bin/graphql-codegen')
    write(binPath)
    assert.equal(findBin(cwd), binPath)
  })

  test('finds generated admin files from supported output folders', ({ assert }) => {
    assert.isNull(findGeneratedFile(cwd))
    assert.isNull(findTypesFile(cwd))

    const generatedPath = resolve(cwd, 'types/generated/admin.generated.d.ts')
    const typesPath = resolve(cwd, 'types/generated/admin.types.d.ts')
    write(generatedPath)
    write(typesPath)

    assert.equal(findGeneratedFile(cwd), generatedPath)
    assert.equal(findTypesFile(cwd), typesPath)
  })

  test('patchScalars replaces Shopify scalar anys with concrete types', ({ assert }) => {
    const typesPath = resolve(cwd, 'types/generated/admin.types.d.ts')
    write(typesPath, [
      'export type Scalars = {',
      '  DateTime: { input: any; output: any }',
      '  JSON: { input: any; output: any }',
      '  Boolean: { input: boolean; output: boolean }',
      '}',
    ].join('\n'))

    patchScalars(cwd)

    const content = readFileSync(typesPath, 'utf-8')
    assert.include(content, 'DateTime: { input: string; output: string }')
    assert.include(content, 'JSON: { input: string; output: string }')
    assert.include(content, 'Boolean: { input: boolean; output: boolean }')
  })

  test('patchScalars is a no-op without generated types', ({ assert }) => {
    assert.doesNotThrow(() => patchScalars(cwd))
  })

  test('extractInterfaceEntries handles missing interfaces, comments, and nested braces', ({ assert }) => {
    const content = [
      'interface GeneratedQueryTypes {',
      '  // ignored comment',
      '  "#graphql query GetThing { shop { name } }": { return: GetThingQuery, variables: GetThingQueryVariables }',
      '  /** ignored block */',
      '  "#graphql query Nested { shop { id } }": { return: NestedQuery, variables: { id: string } }',
      '}',
    ].join('\n')

    assert.deepEqual(extractInterfaceEntries(content, 'MissingTypes'), [])
    assert.deepEqual(extractInterfaceEntries(content, 'GeneratedQueryTypes'), [
      '"#graphql query GetThing { shop { name } }": { return: GetThingQuery, variables: GetThingQueryVariables }',
      '"#graphql query Nested { shop { id } }": { return: NestedQuery, variables: { id: string } }',
    ])
  })

  test('generateBridge creates a stable operations bridge', ({ assert }) => {
    const generatedPath = resolve(cwd, 'types/generated/admin.generated.d.ts')
    write(generatedPath, [
      'export interface GeneratedQueryTypes {',
      '  "#graphql query GetThing { shop { name } }": { return: GetThingQuery, variables: GetThingQueryVariables }',
      '}',
      'export interface GeneratedMutationTypes {',
      '  "#graphql mutation UpdateThing { productUpdate { product { id } } }": { return: UpdateThingMutation, variables: UpdateThingMutationVariables }',
      '}',
      'export type GetThingQuery = { shop: { name: string } }',
      'export type GetThingQueryVariables = {}',
      'export type UpdateThingMutation = { productUpdate: { product: { id: string } } }',
      'export type UpdateThingMutationVariables = { id: string }',
    ].join('\n'))

    generateBridge(cwd)
    const bridgePath = resolve(cwd, 'types/openshop-operations.d.ts')
    const first = readFileSync(bridgePath, 'utf-8')
    generateBridge(cwd)
    const second = readFileSync(bridgePath, 'utf-8')

    assert.equal(second, first)
    assert.include(first, '// Auto-generated by openshop codegen')
    assert.include(first, "from './generated/admin.generated'")
    assert.include(first, 'interface OpenShopQueries')
    assert.include(first, 'interface OpenShopMutations')
    assert.include(first, 'GetThingQueryVariables')
    assert.include(first, 'UpdateThingMutationVariables')
  })

  test('generateBridge is a no-op without operation entries', ({ assert }) => {
    const generatedPath = resolve(cwd, 'types/generated/admin.generated.d.ts')
    write(generatedPath, 'export interface GeneratedQueryTypes {}')

    assert.doesNotThrow(() => generateBridge(cwd))
    assert.isFalse(existsSync(resolve(cwd, 'types/openshop-operations.d.ts')))
  })
})
